"""
Django settings for not_pointless project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import json
import boto3
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Load .env file only in development
if os.getenv('ENVIRONMENT') != 'production':
    load_dotenv()

class mySecrets:
    """
    Class to manage secrets retrieval with caching to avoid multiple API calls
    """
    def __init__(self):
        self.cache = {}
        self.region_name = "us-east-1"
    
    def get_secret(self, *, secret_name, default_if_not_found=None, secret_sub_key=None):
        """
        Generic secret retrieval function with three-step fallback:
        1. Try AWS Secrets Manager
        2. Try .env file / environment variable
        3. Return default_if_not_found
        
        Parameters:
        - secret_name (str): Name of the secret to retrieve (required)
        - default_if_not_found: Value to return if secret is not found (default=None)
        - secret_sub_key (str): If the secret is a dictionary, get this specific key (default=None)
        """
        # Check if we already have this secret in cache
        if secret_name in self.cache:
            secret_value = self.cache[secret_name]
            # If we need a sub-key and the cached value is a dict, return the sub-key
            if secret_sub_key is not None and isinstance(secret_value, dict):
                return secret_value.get(secret_sub_key, default_if_not_found)
            return secret_value
        
        # Step 1: Try AWS Secrets Manager
        try:
            session = boto3.session.Session()
            client = session.client(
                service_name='secretsmanager',
                region_name=self.region_name
            )
            get_secret_value_response = client.get_secret_value(
                SecretId=secret_name
            )
            secret = get_secret_value_response['SecretString']
            try:
                # Try to parse as JSON (for dictionary secrets)
                parsed_secret = json.loads(secret)
                # Cache the parsed secret
                self.cache[secret_name] = parsed_secret
                # If a sub-key was requested, return that specific value
                if secret_sub_key is not None:
                    return parsed_secret.get(secret_sub_key, default_if_not_found)
                return parsed_secret
            except json.JSONDecodeError:
                # If not valid JSON, it's a string secret
                self.cache[secret_name] = secret
                return secret
        except Exception as e:
            # AWS Secrets Manager failed, continue to step 2
            pass
        
        # Step 2: Try environment variable / .env file
        env_value = os.getenv(secret_name)
        if env_value is not None:
            # Cache the environment value
            self.cache[secret_name] = env_value
            return env_value
        
        # Step 3: Return default value
        return default_if_not_found

# Create a singleton instance of mySecrets
secrets_manager = mySecrets()

# For backward compatibility
def get_secret(secret_name, default_if_not_found=None):
    """
    Legacy function for backward compatibility.
    Delegates to the new secrets_manager.get_secret method.
    """
    return secrets_manager.get_secret(
        secret_name=secret_name, 
        default_if_not_found=default_if_not_found
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-53q+)n(fti3@35hxb3dstzqpw94&x_tp899f-ig9%d$#ldktzk'
SECRET_KEY = secrets_manager.get_secret(
    secret_name='SECRET_KEY', 
    default_if_not_found='insecure-dev-key-change-me'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# Production settings
ALLOWED_HOSTS = [
    'notpointless.ft1.us',
    '.amazonaws.com',
    ".awsapprunner.com",
    'localhost',
    '127.0.0.1',
    os.getenv("ALLOWED_HOST", "*")
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'not_pointless.apps.NotPointlessConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'not_pointless.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'not_pointless.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration using the new secrets_manager class
# This simplifies the previous approach by using the secret_sub_key parameter
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': secrets_manager.get_secret(
            secret_name="NotPointlessPostgresqlPassword", 
            secret_sub_key='dbname',
            default_if_not_found=secrets_manager.get_secret(
                secret_name='DB_NAME', 
                default_if_not_found='postgres'
            )
        ),
        'USER': secrets_manager.get_secret(
            secret_name="NotPointlessPostgresqlPassword", 
            secret_sub_key='username',
            default_if_not_found=secrets_manager.get_secret(
                secret_name='DB_USER', 
                default_if_not_found='postgres'
            )
        ),
        'PASSWORD': secrets_manager.get_secret(
            secret_name="NotPointlessPostgresqlPassword", 
            secret_sub_key='password',
            default_if_not_found=secrets_manager.get_secret(
                secret_name='DB_PASSWORD', 
                default_if_not_found=''
            )
        ),
        'HOST': secrets_manager.get_secret(
            secret_name="NotPointlessPostgresqlPassword", 
            secret_sub_key='host',
            default_if_not_found=secrets_manager.get_secret(
                secret_name='DB_HOST', 
                default_if_not_found='dev-notpointless.cybcmwkoc02f.us-east-1.rds.amazonaws.com'
            )
        ),
        'PORT': secrets_manager.get_secret(
            secret_name="NotPointlessPostgresqlPassword", 
            secret_sub_key='port',
            default_if_not_found=secrets_manager.get_secret(
                secret_name='DB_PORT', 
                default_if_not_found='5432'
            )
        ),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
